// <auto-generated />
using LojaVirtual.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LojaVirtual.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20201110135729_AdicionaUsuario")]
    partial class AdicionaUsuario
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LojaVirtual.Models.Acesso.Usuario", b =>
                {
                    b.Property<uint>("IdUsuario")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(35);

                    b.Property<uint>("IdCliente");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 1)))
                        .HasColumnType("CHAR(1)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdCliente");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("LojaVirtual.Models.Cliente.Cliente", b =>
                {
                    b.Property<uint>("IdCliente")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("IdCliente");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("LojaVirtual.Models.Acesso.Usuario", b =>
                {
                    b.HasOne("LojaVirtual.Models.Cliente.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
